### ISSUE TITLE
Implement Terminal state control channels and status channels

### ISSUE THREAD

**Issue by Karl-G1** [ni/niveristand-aim-milStd1553-custom-device#60]
To enable users to control and monitor the state of the simulated 1553 Terminals (including BC and RTs) in their system, we should implement the state control and status channels for each terminal. 

Currently these are scripted for each terminal but not used in the engine. We will remove scripting them until they are implemented fully, so this issue is a placeholder for future enhancement.

![image](https://user-images.githubusercontent.com/31290917/179248802-fc41a5ae-8f14-4554-a82c-0101bcba72b5.png)

**Comment by papowerNI** [comment]
Fixed with PR #80
