### ISSUE TITLE
Tests have hard coded hardware parameters, but would be better if they were part of a configuration file

### ISSUE THREAD

**Issue by papowerNI** [ni/niveristand-aim-milStd1553-custom-device#66]
**Is your feature request related to a problem? Please describe.**
This could be a problem if tests are run on systems with hardware in different locations in the future, or if developers want to quickly run the test suite without changing hardcoded values or setting up an identical system to the ATS.

**Describe the solution you'd like**
They could be put in an ini file like targets.ini or another configuration file.

**Describe alternatives you've considered**
The way it is now can work, it just pushes people toward having identical hardware setups for all hardware and development, which could lead to bugs slipping through.

**Additional context**

**Comment by Karl-G1** [comment]
I mocked up a couple different fixes for this in the [dev/test_config_file](https://github.com/ni/niveristand-aim-milStd1553-custom-device/tree/dev/test_config_file) branch. Both attempt to leverage existing IP in the Test Tools repo. By modifying targets.ini and config.ini in `Custom Device Support\Tests\Shared`, you could deploy the system tests to a different target, slot, BIU, etc.

1) Create a config.ini file that contains **overrides** and apply them **after scripting** the system definition
This is probably the easiest implementation, as it only affects the shared `Create and Script 1553 System Definition.vi`.
I used two of the internal testing tools VIs to parse and apply the overrides on a per-channel basis to the system definition. The only catch is that this is usually done while deploying, so the test tools VIs create a copy of the system definition file. I worked around that by copying the file back to the original location and deleting the copy.
![image](https://user-images.githubusercontent.com/31290917/181593377-ad7f0b75-3b62-406d-baca-5052a915ca0b.png)
![image](https://user-images.githubusercontent.com/31290917/181593530-06cce0de-d262-4d53-a89e-2a082c3f4c7b.png)

2) Create a config.ini file that contains **overrides** and parse them **while deploying** the system definition
This is how the config file is _meant_ to be used: applied during the `OpenVeriStandConnection.vi` call. We could do this, except it would affect every test VI / globalSetup VI that makes this call. Here's the approach mocked up for `Custom Device Support\Tests\System\Deployment\test Deployment Import Configuration.vi`
![image](https://user-images.githubusercontent.com/31290917/181595667-78e33c1e-38c5-4aac-bce2-b3352294f544.png)


3) Create a config.ini file that contains **properties** and parse them **while scripting** the system definition
I didn't mock this up, as it is was really messy to parse the properties contained in the file before deployment and map them to the contents of the hardware configuration cluster. It's possible, just a lot uglier than the overrides approach.
